### ISSUE TITLE
samit window size

### ISSUE THREAD

**Issue by nicolasdarmanthe** [mic-umcg/samit#4]
The contents of the samit window are cropped when launching samit (image 1). I've had this problem in both samit1.2 and 1.3, but not in previous versions.

A quick fix is to make the samit window size adjustable (image 2) by running 
`samit; set(samit, 'Resize', 'On')`

I tried adding this line to the samit.m file but it wasn't clear to me where the line of code should go.
It would be nice if the contents of the samit window scaled with the size of the window. Using the above command, it is possible to make the samit window larger to accommodate for the contents, but the actual size of the contents remains static. This is a problem on smaller displays since it is not possible to make the window big enough (in height) to accommodate for the entirety of the samit window contents (image 3).

<img width="423" alt="1" src="https://user-images.githubusercontent.com/35124438/42296245-ab407512-8036-11e8-981a-bf5e556cdc11.png">

![2](https://user-images.githubusercontent.com/35124438/42296249-b3c9ef74-8036-11e8-8305-86e91e12227b.png)

<img width="600" alt="3" src="https://user-images.githubusercontent.com/35124438/42296250-b9f525a8-8036-11e8-802d-f94060a7cfbb.png">

**Comment by dvallezgarcia** [comment]
Thanks for reporting the issue. Can you give me further information about the resolution that you are using in the display? I would like to replicate the issue, to make sure it is properly solved.

**Comment by nicolasdarmanthe** [comment]
I'm using a 2560-by-1600 13 inch MacBook Pro (2015) display

**Comment by dvallezgarcia** [comment]
Can you try this fix? Replace samit.m and samit.fig with the ones attached here. It is not the most elegant solution, but it might work. At this moment, I cannot test with the resolution that you have...

[samit_fixResize.zip](https://github.com/mic-umcg/samit/files/2192486/samit_fixResize.zip)

**Comment by nicolasdarmanthe** [comment]
Hi David,

Sorry for the delay in response. That fixed the problem! It might not be elegant, but function over form ;)
